/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package keyvault.models;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The SAS definition update parameters.
 */
public class SasDefinitionUpdateParameters {
    /**
     * Sas definition update metadata in the form of key-value pairs.
     */
    @JsonProperty(value = "parameters")
    private Map<String, String> parameters;

    /**
     * The attributes of the SAS definition.
     */
    @JsonProperty(value = "attributes")
    private SasDefinitionAttributes sasDefinitionAttributes;

    /**
     * Application specific metadata in the form of key-value pairs.
     */
    @JsonProperty(value = "tags")
    private Map<String, String> tags;

    /**
     * Get the parameters value.
     *
     * @return the parameters value
     */
    public Map<String, String> parameters() {
        return this.parameters;
    }

    /**
     * Set the parameters value.
     *
     * @param parameters the parameters value to set
     * @return the SasDefinitionUpdateParameters object itself.
     */
    public SasDefinitionUpdateParameters withParameters(Map<String, String> parameters) {
        this.parameters = parameters;
        return this;
    }

    /**
     * Get the sasDefinitionAttributes value.
     *
     * @return the sasDefinitionAttributes value
     */
    public SasDefinitionAttributes sasDefinitionAttributes() {
        return this.sasDefinitionAttributes;
    }

    /**
     * Set the sasDefinitionAttributes value.
     *
     * @param sasDefinitionAttributes the sasDefinitionAttributes value to set
     * @return the SasDefinitionUpdateParameters object itself.
     */
    public SasDefinitionUpdateParameters withSasDefinitionAttributes(SasDefinitionAttributes sasDefinitionAttributes) {
        this.sasDefinitionAttributes = sasDefinitionAttributes;
        return this;
    }

    /**
     * Get the tags value.
     *
     * @return the tags value
     */
    public Map<String, String> tags() {
        return this.tags;
    }

    /**
     * Set the tags value.
     *
     * @param tags the tags value to set
     * @return the SasDefinitionUpdateParameters object itself.
     */
    public SasDefinitionUpdateParameters withTags(Map<String, String> tags) {
        this.tags = tags;
        return this;
    }

}
